[functions]
  external_node_modules = ["express"]
  node_bundler = "esbuild"
[build]
  publish = "dist"

[[redirects]]
  from = "/api/users"
  to = "/.netlify/functions/users"
  status = 200

[[redirects]]
  from = "/api/users/*"
  to = "/.netlify/functions/users/:splat"
  status = 200

[[redirects]]
  force = true
  from = "/api/*"
  status = 200
  to = "/.netlify/functions/index/:splat"